{% set name = "torch_geometric" %}
{% set version = "2.0.3" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59c41993a0f6cc0e29efa6ca6274cc97bd6557e54bf7d3d38213933f821701c6

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools
  run:
    - googledrivedownloader
    - jinja2
    - networkx
    - numpy
    - pandas
    - pyparsing
    - python >=3.6
    - python-louvain
    - requests
    - rdflib
    - scikit-learn
    - scipy
    - tqdm
    - pytorch
    - pytorch_sparse
    - pyyaml
    - yacs

test:
  imports:
    - torch_geometric

about:
  home: https://github.com/rusty1s/pytorch_geometric
  summary: Geometric Deep Learning Extension Library for PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_geometric

extra:
  recipe-maintainers:
    - bubblyorca
    - mxr-conda
    - sugatoray
