{% set name = "torch_geometric" %}
{% set version = "2.6.1" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f18f9d0fc4d2239d526221e4f22606a4a3895b5d965a9856d27610a3df662c6

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - flit
  run:
    - python >={{ python_min }}
    - pytorch

    # Required deps
    - aiohttp
    - fsspec
    - jinja2
    - numpy
    - psutil >=5.8.0
    - pyparsing
    - requests
    - tqdm

    # Full deps
    - scipy
    - scikit-learn
    - ase
    - captum
    - graphviz
    - h5py
    - matplotlib-base
    - networkx
    - numba
    - opt_einsum
    - pandas
    - pgmpy
    - pynndescent
    # - pytorch-memlab  # not yet on conda forge
    - rdflib
    - rdkit
    - scikit-image
    - statsmodels
    - sympy
    - tabulate
    - torchmetrics
    - trimesh

test:
  requires:
    - python {{ python_min }}
  imports:
    - torch_geometric

about:
  home: https://github.com/pyg-team/pytorch_geometric
  summary: Geometric Deep Learning Extension Library for PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pyg-team/pytorch_geometric

extra:
  recipe-maintainers:
    - jan-janssen
    - bubblyorca
    - mxr-conda
    - mikemhenry
