{% set version = "2.6.1" %}
{% set python_min = "3.9" %}

package:
  name: pytorch_geometric
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/torch_geometric/torch_geometric-{{ version }}.tar.gz
  sha256: 1f18f9d0fc4d2239d526221e4f22606a4a3895b5d965a9856d27610a3df662c6

build:
  number: 2
  noarch: python

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

outputs:
  - name: pytorch_geometric
    # Parity with "torch_geometry" pypi package
    # Parity with "pyg::pyg" and "pyg::pytorch-geometric" conda packages
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - flit-core >=3.2,<4
        - pip
      run:
        - python >={{ python_min }}
        - aiohttp
        - fsspec
        - jinja2
        - numpy
        - psutil >=5.8.0
        - pyparsing
        - requests
        - tqdm

    test:
      imports:
        - torch_geometric
        - torch_geometric.nn
        - torch_geometric.data
        - torch_geometric.utils
        - torch_geometric.datasets
        - torch_geometric.transforms
      requires:
        - python {{ python_min }}
        - pytorch-cpu >=2.5.1  # first conda-forge version for all platforms
        - pip
      commands:
        - pip check

  - name: pytorch_geometric-graphgym
    # Parity with "torch_geometry[graphgym]" pypi package
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('pytorch_geometric', exact=True) }}
        - protobuf #<4.21
        - pytorch-lightning #<2.3.0
        - yacs

    test:
      imports:
        - torch_geometric
        - torch_geometric.nn
        - torch_geometric.data
        - torch_geometric.utils
        - torch_geometric.datasets
        - torch_geometric.transforms
        - torch_geometric.graphgym
      requires:
        - python {{ python_min }}
        - pytorch-cpu >=2.5.1  # first conda-forge version for all platforms
        - pip
      commands:
        - pip check

  - name: pytorch_geometric-modelhub
    # Parity with "torch_geometry[modelhub]"
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('pytorch_geometric', exact=True) }}
        - huggingface_hub

    test:
      imports:
        - torch_geometric
        - torch_geometric.nn
        - torch_geometric.data
        - torch_geometric.utils
        - torch_geometric.datasets
        - torch_geometric.transforms
        - torch_geometric.nn.model_hub
      requires:
        - python {{ python_min }}
        - pytorch-cpu >=2.5.1  # first conda-forge version for all platforms
        - pip
      commands:
        - pip check

about:
  home: https://github.com/pyg-team/pytorch_geometric
  summary: Graph Neural Network Library for PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pyg-team/pytorch_geometric

extra:
  recipe-maintainers:
    - jan-janssen
    - bubblyorca
    - mxr-conda
    - mikemhenry
    - jamesmyatt
