{% set version = "2.6.1" %}
{% set python_min = "3.8" %}

package:
  name: pytorch_geometric
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/torch_geometric/torch_geometric-{{ version }}.tar.gz
  sha256: 1f18f9d0fc4d2239d526221e4f22606a4a3895b5d965a9856d27610a3df662c6

build:
  number: 2
  noarch: python

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - torch_geometric
    - torch_geometric.nn
    - torch_geometric.data
    - torch_geometric.utils
    - torch_geometric.datasets
    - torch_geometric.transforms
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

outputs:
  - name: pyg
    # Parity with "torch_geometry" pypi package
    # Parity with "pyg::pyg" and "pyg::pytorch-geometric" conda packages
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python {{ python_min }}
        - flit-core >=3.2,<4
        - pip
      run:
        - python >={{ python_min }}
        - aiohttp
        - fsspec
        - jinja2
        - numpy
        - psutil >=5.8.0
        - pyparsing
        - requests
        - tqdm

  - name: pyg-graphgym
    # Parity with "torch_geometry[graphgym]" pypi package
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('pyg', exact=True) }}
        - protobuf <4.21
        - pytorch-lightning <2.3.0
        - yacs

  - name: pyg-modelhub
    # Parity with "torch_geometry[modelhub]"
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('pyg', exact=True) }}
        - huggingface_hub
    test:
      imports:
        - torch_geometric.nn.model_hub

  - name: pyg-full
    # Parity with "torch_geometry[full]" pypi package
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('pyg-graphgym', exact=True) }}
        - {{ pin_subpackage('pyg-modelhub', exact=True) }}
        - scipy
        - scikit-learn
        - ase
        - captum <0.7.0
        - graphviz
        - h5py
        - matplotlib-base
        - networkx
        - numba <0.60.0
        - opt_einsum
        - pandas
        - pgmpy
        - pynndescent
        # - pytorch-memlab  # not yet on conda forge
        - rdflib
        - rdkit
        - scikit-image
        - statsmodels
        - sympy
        - tabulate
        - torchmetrics
        - trimesh

  - name: pytorch_geometric
    # Synonym for pyg-full sub-package
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('pyg-full', exact=True) }}

about:
  home: https://github.com/pyg-team/pytorch_geometric
  summary: Graph Neural Network Library for PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pyg-team/pytorch_geometric

extra:
  recipe-maintainers:
    - jan-janssen
    - bubblyorca
    - mxr-conda
    - mikemhenry
